baseURL = "http://calista-test.org/"
languageCode = "en-us"
title = "Timer | Responsive Multipurpose Bootstrap Hugo Template"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.nav]]
name    = "About"
url     = "about"
weight  = 2
[[menu.nav]]
name    = "Service"
url     = "service"
weight  = 3
[[menu.nav]]
name    = "Gallery"
url     = "gallery"
weight  = 4
[[menu.nav]]
name    = "Blog"
url     = "blog"
weight  = 5
[[menu.nav]]
name    = "Contact"
url     = "contact"
weight  = 6

# Site Params
[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "Airspace Hugo theme"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"

# Banner Section
[params.banner]
enable  = true
bgImage = "images/slider.jpg"
heading = "LAND"
description = "LOCAL.AREA.NETWORKING.DUH"
# button
btn     = true
btnText = "Download More"
btnURL  = "https://themefisher.com/"

# flip text
[[params.banner.flipText]]
title   = "LOCAL"
[[params.banner.flipText]]
title   = "AREA"
[[params.banner.flipText]]
title   = "NETWORKING"

# Homepage About Section
[params.about]
enable  = true
title   = "ABOUT LAND"
content = "KXDSKCJDNJKNDJKNKDDNS"
image   = "images/about/about.jpg"

# Call to Action
[params.cta]
enable  = true
title   = "SO WHAT YOU DO YOU THINK ABOUT LAND?"
content = "FEEDBACK/CRITISM IS ALWAYS WELCOMED."
btnText = "Give Feedback"
btnURL  = "/contact"

# Portfolio Section On Homepage
[params.portfolio]
enable  = true
title   = "Latest Events"
subtitle= "Join LAND and learn about all the tech community."

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "#"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "#"

[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "#"
